version: "3"

services:
  redis-server:
    image: redis
    container_name: redis-server
    networks:
      - app-network
    restart: always
  api:
    build:
      context: .
    container_name: api-server
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - port=80
    links:
      - redis-server
    ports:
      - 80:80

networks:
  app-network:
    driver: bridge